# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
